### ISSUE TITLE
清明假期合肥开发者聚会 (draft)

### ISSUE THREAD

**Issue by firede** [anhui-dev/meeting#1]
* 时间：4月5日
* 地点：市内
* 费用：AA（……如果没赞助商）

## 技术分享

分享主题收集中，如果你有 **想做** 或 **想听** 的分享，请回帖。

> _大家~~可能~~感兴趣的话题：程序员~~养生~~健康，买房攻略……_

## 聚餐 & 面基

~~待定~~ 报名人数过少，聚会改为面基 :trollface: 

## 感兴趣？

为了统计人数，针对本帖：

* **感兴趣**请点 ❤️ 
* **确定参加**请点 👍 

任何提议都可回复本帖。

**Comment by peqing** [comment]
我先赞一个再说

**Comment by BigNerdCoding** [comment]
我报名一个

**Comment by zhusimaji** [comment]
赞一个

**Comment by boilingnoise** [comment]
赞

**Comment by ifsc01** [comment]
🆒

**Comment by firede** [comment]
活动记录
---
4月5日 14:00~17:00 研磨咖啡金域华府店
参加人员：@firede, @BigNerdCoding, 谷阳
